# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a2f692197e18ad5b152b729949f0917f3e7adfac9f36947aa4dd9e3b25cc82dd46e6544c3292e8ebf58d8f3887c79c157e9c1fb13db2d7abccaf819ba19ca4e

test:
  secret_key_base: 2add08a29f2a5097dae377948b739118a3c11325470ad50d8db9a61b8ad17a52f9ad4cc10b7bf098181416319518e6e24cedeb4c7e530537bd1f8bd4f371d0d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
